//function _(array) {};
/**
 * @param arg
 * @return {UnderscoreObject}
 */
var _ = function(array) {};

/** @constructor */
function UnderscoreObject() {};

  UnderscoreObject.prototype.VERSION = '1.1.7';
  UnderscoreObject.prototype.map = function(obj, iterator, context) {};
  UnderscoreObject.prototype.some = function(obj, iterator, context) {};
  UnderscoreObject.prototype.any = function(obj, iterator, context) {};
  UnderscoreObject.prototype.reduce = function(obj, iterator, memo, context) {};
  UnderscoreObject.prototype.foldl = function(obj, iterator, memo, context) {};
  UnderscoreObject.prototype.inject = function(obj, iterator, memo, context) {};
  UnderscoreObject.prototype.reduceRight = function(obj, iterator, memo, context) {};
  UnderscoreObject.prototype.foldr = function(obj, iterator, memo, context) {};
  UnderscoreObject.prototype.find = function(obj, iterator, context) {};
  UnderscoreObject.prototype.detect = function(obj, iterator, context) {};
  UnderscoreObject.prototype.filter = function(obj, iterator, context) {};
  UnderscoreObject.prototype.select = function(obj, iterator, context) {};
  UnderscoreObject.prototype.reject = function(obj, iterator, context) {};
  UnderscoreObject.prototype.every = function(obj, iterator, context) {};
  UnderscoreObject.prototype.all = function(obj, iterator, context) {};
  UnderscoreObject.prototype.include = function(obj, target) {};
  UnderscoreObject.prototype.contains = function(obj, target) {};
  UnderscoreObject.prototype.invoke = function(obj, method) {};
  UnderscoreObject.prototype.pluck = function(obj, key) {};
  UnderscoreObject.prototype.max = function(obj, iterator, context) {};
  UnderscoreObject.prototype.min = function(obj, iterator, context) {};
  UnderscoreObject.prototype.sortBy = function(obj, iterator, context) {};
  UnderscoreObject.prototype.groupBy = function(obj, iterator) {};
  UnderscoreObject.prototype.sortedIndex = function(array, obj, iterator) {};
  UnderscoreObject.prototype.toArray = function(iterable) {};
  UnderscoreObject.prototype.size = function(obj) {};
  UnderscoreObject.prototype.first = function(array, n, guard) {};
  UnderscoreObject.prototype.head = function(array, n, guard) {};
  UnderscoreObject.prototype.rest = function(array, index, guard) {};
  UnderscoreObject.prototype.tail = function(array, index, guard) {};
  UnderscoreObject.prototype.last = function(array) {};
  UnderscoreObject.prototype.compact = function(array) {};
  UnderscoreObject.prototype.flatten = function(array) {};
  UnderscoreObject.prototype.without = function(array) {};
  UnderscoreObject.prototype.chain = function(array) {};
  UnderscoreObject.prototype.uniq = function(array, isSorted, iterator) {};
  UnderscoreObject.prototype.unique = function(array, isSorted, iterator) {};
  UnderscoreObject.prototype.union = function() {};
  UnderscoreObject.prototype.intersection = function(array) {};
  UnderscoreObject.prototype.intersect = function(array) {};
  UnderscoreObject.prototype.difference = function(array, other) {};
  UnderscoreObject.prototype.zip = function() {};
  UnderscoreObject.prototype.indexOf = function(array, item, isSorted) {};
  UnderscoreObject.prototype.lastIndexOf = function(array, item) {};
  UnderscoreObject.prototype.range = function(start, stop, step) {};
  UnderscoreObject.prototype.bind = function(func, obj) {};
  UnderscoreObject.prototype.bindAll = function(obj) {};
  UnderscoreObject.prototype.memoize = function(func, hasher) {};
  UnderscoreObject.prototype.delay = function(func, wait) {};
  UnderscoreObject.prototype.defer = function(func) {};
  UnderscoreObject.prototype.throttle = function(func, wait) {};
  UnderscoreObject.prototype.debounce = function(func, wait) {};
  UnderscoreObject.prototype.once = function(func) {};
  UnderscoreObject.prototype.wrap = function(func, wrapper) {};
  UnderscoreObject.prototype.compose = function() {};
  UnderscoreObject.prototype.after = function(times, func) {};
  UnderscoreObject.prototype.keys = function(obj) {};
  UnderscoreObject.prototype.values = function(obj) {};
  UnderscoreObject.prototype.functions = function(obj) {};
  UnderscoreObject.prototype.methods = function(obj) {};
  UnderscoreObject.prototype.extend = function(obj) {};
  UnderscoreObject.prototype.defaults = function(obj) {};
  UnderscoreObject.prototype.clone = function(obj) {};
  UnderscoreObject.prototype.tap = function(obj, interceptor) {};
  UnderscoreObject.prototype.isEqual = function(a, b) {};
  UnderscoreObject.prototype.isEmpty = function(obj) {};
  UnderscoreObject.prototype.isElement = function(obj) {};
  UnderscoreObject.prototype.isArray = function(obj) {};
  UnderscoreObject.prototype.isObject = function(obj) {};
  UnderscoreObject.prototype.isArguments = function(obj) {};
  UnderscoreObject.prototype.isFunction = function(obj) {};
  UnderscoreObject.prototype.isString = function(obj) {};
  UnderscoreObject.prototype.isNumber = function(obj) {};
  UnderscoreObject.prototype.isNaN = function(obj) {};
  UnderscoreObject.prototype.isBoolean = function(obj) {};
  UnderscoreObject.prototype.isDate = function(obj) {};
  UnderscoreObject.prototype.isRegExp = function(obj) {};
  UnderscoreObject.prototype.isNull = function(obj) {};
  UnderscoreObject.prototype.isUndefined = function(obj) {};
  UnderscoreObject.prototype.noConflict = function() {};
  UnderscoreObject.prototype.identity = function(value) {};
  UnderscoreObject.prototype.times = function (n, iterator, context) {};
  UnderscoreObject.prototype.mixin = function(obj) {};
  UnderscoreObject.prototype.uniqueId = function(prefix) {};
  UnderscoreObject.prototype.templateSettings = {};
  UnderscoreObject.prototype.template = function(str, data) {};
