#!/bin/sh

# vaccine.js must NOT be in the source list.
source_dir='src'
app_name='underscore'

sources='
src/each.js
src/objects.js
src/utils.js
src/functions.js
src/collections.js
src/arrays.js
src/index.js
'


echo '//     Underscore.js 1.4.1
//     http://underscorejs.org
//     (c) 2009-2012 Jeremy Ashkenas, DocumentCloud Inc.
//     Underscore may be freely distributed under the MIT license.
(function() {'
cat src/vaccine.js   # Output vaccine.js separately

for file in $sources
do
  name="$app_name/$(echo "$file" | sed -e "s#^$source_dir/##" -e 's/\.js//')"
  test "X$name" = "X$app_name/index" && name=$app_name
  echo "define('$name', function(require, exports, module) {"
  cat $file
  echo '});'
done

echo '}());'
